version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - ci
      - dependencies
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "-"
    schedule:
      day: saturday
      interval: weekly
      time: "09:00"
